### ISSUE TITLE
Doesnt work with new Chrome

### ISSUE THREAD

**Issue by swarad07** [ironexdev/zoom#1]
Hi I tried the latest library it doesn't work with new Chrome, works on FF and Safari. 

An older version is linked here https://www.cssscript.com/touch-enabled-image-zoom-plugin-javascript/ and it works just fine.

Could you help with fixing the compatibility with Chrome?

**Comment by jeremyrperry** [comment]
@swarad07 I checked out your problem since it could be related to mine.  I personally didn't have any issues with this library except for IE11.  I might be able to help you if you can put up an example somewhere that's publicly accessible.

**Comment by swarad07** [comment]
Hi @jeremyrperry, here is the public URL of what I am facing. You need to try this on mobile though, as on desktop this works just fine --even in mobile resolutions.

Link1: https://codepen.io/swarad07/full/yZoxJy

This pen has the library source from the master branch of this repo. On Android - Chrome 71.0.357 - OnePlus 6T this doesnt work.

Link2: https://codepen.io/swarad07/full/QYMVLP

This pen has the source from https://www.cssscript.com/demo/touch-enabled-image-zoom-plugin-javascript/. This works just fine in all browsers, desktop as well as mobile.

**Comment by swarad07** [comment]
Also on IE11 the ES6 syntax doesnt work for zoom function declaration.

If you change it to below where you initialize the arguments inside rather than inline as it should be for ES5, it works.

```function zoom(classNames, settings) {
  var classNames = classNames || {};
  var settings = settings || {};```

**Comment by ironexdev** [comment]
resolved by pull request by @jeremyrperry in https://github.com/ironexdev/zoom/issues/2
